spammaster.settings:
  type: config_object
  label: 'Spam Master Settings'
  mapping:
    spammaster:
      type: mapping
      mapping:
        version:
          type: textfield
          label: ''
        type:
          type: textfield
          label: ''
        license_key:
          type: textfield
          label: ''
        license_status:
          type: textarea
          label: ''
        license_alert_level:
          type: textarea
          label: ''
        license_protection:
          type: textfield
          label: ''
        license_probability:
          type: textfield
          label: ''
        block_message:
          type: textfield
          label: ''
        basic_firewall:
          type: select
          label: '1'
        basic_registration:
          type: select
          label: '1'
        basic_comment:
          type: select
          label: '1'
        basic_contact:
          type: select
          label: '1'
        signature_registration:
          type: select
          label: '1'
        signature_login:
          type: select
          label: '1'
        signature_comment:
          type: select
          label: '1'
        signature_contact:
          type: select
          label: '1'
        email_alert_3:
          type: select
          label: '1'
        email_daily_report:
          type: select
          label: '0'
        email_weekly_report:
          type: select
          label: '0'
        email_improve:
          type: select
          label: '1'
