spammaster.settings:
  type: config_object
  mapping:
    type:
      type: textfield
      label: ''
    license_key:
      type: textfield
      label: ''
    license_status:
      type: textarea
      label: ''
    license_alert_level:
      type: textarea
      label: ''
    license_protection:
      type: textfield
      label: ''
    license_probability:
      type: textfield
      label: ''
spammaster.settings_protection:
  type: config_object
  mapping:
    block_message:
      type: textfield
      label: ''
    basic_firewall:
      type: select
      label: '1'
    basic_registration:
      type: select
      label: '1'
    basic_comment:
      type: select
      label: '1'
    basic_contact:
      type: select
      label: '1'
    extra_recaptcha:
      type: select
      label: '0'
    extra_recaptcha_api_key:
      type: textfield
      label: ''
    extra_recaptcha_api_secret_key:
      type: textfield
      label: ''
    extra_recaptcha_login:
      type: select
      label: '0'
    extra_recaptcha_registration:
      type: select
      label: '0'
    extra_recaptcha_comment:
      type: select
      label: '0'
    extra_recaptcha_contact:
      type: select
      label: '0'
    extra_honeypot:
      type: select
      label: '1'
    extra_honeypot_login:
      type: select
      label: '1'
    extra_honeypot_registration:
      type: select
      label: '1'
    extra_honeypot_comment:
      type: select
      label: '1'
    extra_honeypot_contact:
      type: select
      label: '1'
    signature_registration:
      type: select
      label: '1'
    signature_login:
      type: select
      label: '1'
    signature_comment:
      type: select
      label: '1'
    signature_contact:
      type: select
      label: '1'
    email_alert_3:
      type: select
      label: '1'
    email_daily_report:
      type: select
      label: '0'
    email_weekly_report:
      type: select
      label: '0'
    email_improve:
      type: select
      label: '1'
spammaster.settings_buffer:
  type: config_object
  mapping:
spammaster.settings_log:
  type: config_object
  mapping:
